services:
  app:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.<challenge-name>.rule=Host(`<challenge-name>.sucss.org`)"
      - "traefik.http.routers.<challenge-name>.tls=true"
      - "traefik.http.routers.<challenge-name>.middlewares=authentik@file"
      - "traefik.http.services.<challenge-name>.loadbalancer.server.port=8000"

    networks:
      - traefik

networks:
  traefik:
    external: true